name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Artifact 1
        run: |
          mkdir -p dist
          echo "Content of Artifact 1" > dist/artifact1.txt

      - name: Upload Artifact 1
        uses: actions/upload-artifact@v3
        with:
          name: artifact1
          path: dist/artifact1.txt

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Artifact 2
        run: |
          mkdir -p dist
          echo "Content of Artifact 2" > dist/artifact2.txt

      - name: Upload Artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: artifact2
          path: dist/artifact2.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact 1
        uses: actions/download-artifact@v3
        with:
          name: artifact1
          path: dist

      - name: Download Artifact 2
        uses: actions/download-artifact@v3
        with:
          name: artifact2
          path: dist

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
