name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Artifact 1
        run: |
          mkdir -p artifacts
          echo "Content of Artifact 1" > artifacts/artifact1.txt

      - name: Upload Artifact 1
        uses: actions/upload-artifact@v3
        with:
          name: artifact1
          path: artifacts/artifact1.txt

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Artifact 2
        run: |
          mkdir -p artifacts
          echo "Content of Artifact 2" > artifacts/artifact2.txt

      - name: Upload Artifact 2
        uses: actions/upload-artifact@v3
        with:
          name: artifact2
          path: artifacts/artifact2.txt

  deploy:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact 1
        uses: actions/download-artifact@v3
        with:
          name: artifact1
          path: artifacts

      - name: Download Artifact 2
        uses: actions/download-artifact@v3
        with:
          name: artifact2
          path: artifacts

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p public
          mv artifacts/* public/
          echo "github-pages deployment" > public/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
